# Generated by Django 4.2.4 on 2023-11-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=220)),
                ('lastname', models.CharField(max_length=220)),
                ('fathername', models.CharField(max_length=220)),
                ('mothername', models.CharField(max_length=220)),
                ('dob', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('fathermobilenumber', models.CharField(max_length=220)),
                ('mothermobilenumber', models.CharField(max_length=220)),
                ('gender', models.CharField(max_length=220)),
            ],
        ),
    ]
